replicaCount: 1

enterpriseEdition: 
  enabled: false
  image:
    repository: portainer/portainer-ee
    tag: 2.39.1
    pullPolicy: Always

image:
  repository: portainer/portainer-ce
  tag: 2.39.1
  pullPolicy: Always

imagePullSecrets: []

nodeSelector: {}
tolerations: []

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

localMgmt: true

service:
  type: NodePort
  httpPort: 9000
  httpsPort: 9443
  httpNodePort: 30777
  httpsNodePort: 30779
  edgePort: 8000
  edgeNodePort: 30776
  annotations: {}

tls:
  force: false
  existingSecret: ""

trusted_origins:
    enabled: false
    domains: ""

mtls:
  enable: false
  existingSecret: ""

dbEncryption:
  existingSecret: ""

adminPassword:
  existingSecret: ""

feature:
  flags: []

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts:
    - host:
      paths: []
  tls: []

extraEnv: []

resources: {}

persistence:
  enabled: true
  size: "10Gi"
  annotations: {}
  storageClass:
  existingClaim:
