image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: latest

auth:
  postgresPassword: admin123
  username: myuser
  password: mypassword
  database: homeladb

primary:
  persistence:
    enabled: true
    storageClass: nfs-client
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    
  service:
    type: NodePort
    nodePorts:
      postgresql: 30432
  
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

metrics:
  enabled: false

tests:
  enabled: false
