postgresql:
  image:
    registry: ghcr.io
    repository: bitnami/postgresql
    tag: 16.3.0
  
  service:
    type: ClusterIP
    ports:
      - name: postgresql
        port: 5432
        targetPort: postgresql

  auth:
    postgresPassword: admin123
    username: myuser
    password: mypassword
    database: mydb

  primary:
    persistence:
      enabled: true
      storageClass: nfs-client
      accessModes:
        - ReadWriteOnce
      size: 10Gi

  metrics:
    enabled: false