auth:
  postgresPassword: admin123
  username: myuser
  password: mypassword
  database: mydb

primary:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
    accessModes:
      - ReadWriteOnce

service:
  type: ClusterIP

metrics:
  enabled: false