{{- if .Values.adminPassword.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminPassword.existingSecret | default (printf "%s-admin-password" (include "portainer.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portainer.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.adminPassword.password | b64enc }}
{{- end }}