replicaCount: 3

image:
  repository: bobieaditya03/myapp
  tag: v18

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx

  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
        
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: myapp

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: myapp

persistence:
  enabled: true
  size: "2Gi"
  storageClassName: nfs-client
  accessMode: ReadWriteMany